# ----------------------------------------
# Docker Compose Configuration for PHP 7.4 Development Environment
# ----------------------------------------
# Author: CHERKI Kaisser
# Email: kcherki@live.fr
# GitHub: https://github.com/kcherki
# Version: 1.0.0
# Last Updated: 2024-03-31
# ----------------------------------------
version: '3.8'

services:
  web:
    build:
      context: ./docker
    dns:
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: ma_base
      MYSQL_USER: mon_user
      MYSQL_PASSWORD: mon_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: 